package com.service;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.document.Player;
import com.repository.IPlayerOTMRepo;

@Service("otmservice")
public class PlayerOTMServiceImpl implements IPlayerOTMService {
	
	@Autowired
	IPlayerOTMRepo repo;

	@Override
	public String savePlayerData(Player p) {
		int id = repo.save(p).getPId();
		return "Player saved with ID- "+id;
	}

    // Remember one thing when we are saving the id value manually in all the document class then it will also be there in the
	// nested document in the database as opposite of when the id value is generated by mongodb itself
	@Override
	public void getPlayerData(int id) {
		Optional<Player> opt = repo.findById(id);
		if(opt.isPresent()) {
		   System.out.println("Player Info -> "+opt.get());
		   opt.get().getSports().forEach(s->{
			   System.out.println("Sport Info -> "+s);
		   });
           opt.get().getMedals().forEach((m,n)->{
        	       System.out.println("Event Name -> "+m+"  , Medal Info -> "+n);
		   });
		   
		}else {
			System.out.println("Player not found with the ID- "+id);
		}	
	}

}
