# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: hiber
    password: orhiber1905
    oracleucp:
      max-pool-size: 1000
      min-idle: 10
      max-connection-reuse-time: 100000
    type: oracle.ucp.jdbc.PoolDataSourceImpl
