# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdb
    username: root
    password: samRoot-16
    hikari:
      maximum-pool-size: 1000
      minimum-idle: 10
      max-lifetime: 100000
